entry{
  limit_scans = false,
  scan_num = 0,
  windowing = true,
  time_dom = false,
  scan_win = 10,
  plot_scalar = true,
  sd_mag = false,
  file_dir = "ScratchData",
  scan_start = 1,
  file_out = false,
  freq_dom = true,
  plot_hist = false,
  tx = 1,
  mag_sd = true,
  rx = 0,
  log_scale = false,
  sd_phase = false,
  sd_q = false,
  plot_image = false,
  sd_i = false,
}
